### ISSUE TITLE
Question about customData format to send?

### ISSUE THREAD

**Issue by erocheleau** [coveo/coveo.analytics.js#156]
I am using the SimpleAPI for the coveo.analytics lib like so:

`coveoua('init', token, endpoint);`

And then trying to send a pageView event like this:

```
var pageViewEvent = {
        contentIdKey: contentIdKey,
        contentIdValue: contentIdValue,
        contentType: contentType,
        customData: customData
      };
coveoua('send', 'pageview', pageViewEvent);
```

The event is being sent fine and with a valid token it gets accepted to UA, however the `customData` part seems to have a weird format:

Here is the structure of what gets sent:

`{"location":"blablabla","referrer":"blablabla","language":"en","title":"myTitle","contentIdKey":"@sfid","contentIdValue":"myValue","contentType":"Case","customData":{"hash":"","customData":{"test":"patate"}}}`

Is it expected to have 2 levels of customData?
`"customData":{"hash":"","customData":{"test":"patate"}}`

From the code it seems like I should not be incorporating my additional data inside a `customData: {OBJECT}` Is this correct?

If it is, maybe it would be worth it to clarify it in the readme/documentation.

**Comment by francoislg** [comment]
Very, very late, but the next release has simplified the whole process and (almost) does not change the payload.

It means that you can now do: 

```
coveoua('send', 'view', {
  ...
  customData: {
   ...
  }
});
```

`pageview` will still behave as usual, all unknown values will be populated in `customData` instead of the main project. I have always found this behavior to be a little too obscure, so I've removed the concept altogether.
